FIND_LIBRARY(IRC_LIBRARY NAMES Communi)
FIND_PATH(IRC_INCLUDE_DIR NAMES "ircglobal.h" PATH_SUFFIXES Communi qt4/Communi )

# message( STATUS ${IRC_LIBRARY})
if( IRC_LIBRARY AND IRC_INCLUDE_DIR )
    message( STATUS "Found libCommuni ${IRC_LIBRARY}, ${IRC_INCLUDE_DIR}")
    set( IRC_FOUND 1 )
else()
    message( STATUS "Could NOT find libCommuni" )
endif()
