FIND_PATH(YAHOO2_INCLUDE_DIR yahoo2.h PATH_SUFFIXES libyahoo2)
MARK_AS_ADVANCED(YAHOO2_INCLUDE_DIR)

FIND_LIBRARY(YAHOO2_LIBRARY yahoo2 )
MARK_AS_ADVANCED(YAHOO2_LIBRARY)

if(YAHOO2_LIBRARY AND YAHOO2_INCLUDE_DIR)
	set( YAHOO2_FOUND 1 )
	message(STATUS "Found libyahoo2: ${YAHOO2_LIBRARY}, ${YAHOO2_INCLUDE_DIR}")
else()
	message(STATUS "Could NOT find libyahoo2 library")
endif()
