/*
 * This file automatically generated by findsound.sh which run by the
 * Makefile found in the Unix Frotz 2.43 source distribution.
 * Copying this nasty hack to find headers which may be in any of several
 * places is not recommended.  I don't want to use autoconf just yet for
 * this project.
 *
 */

#include <sys/soundcard.h>
