name: C/C++ CI

on: [push]

jobs:
  linux:

    runs-on: ubuntu-16.04
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: cmake . -DENABLE_TESTS=ON
    - name: make
      run: make
    - name: make test
      run: make test
