# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
_CONNECTIONERROR = descriptor.EnumDescriptor(
  name='ConnectionError',
  full_name='pbnetwork.ConnectionError',
  filename='ConnectionError',
  values=[
    descriptor.EnumValueDescriptor(
      name='CONNECTION_ERROR_NETWORK_ERROR', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CONNECTION_ERROR_INVALID_USERNAME', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CONNECTION_ERROR_AUTHENTICATION_FAILED', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CONNECTION_ERROR_AUTHENTICATION_IMPOSSIBLE', index=3, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CONNECTION_ERROR_NO_SSL_SUPPORT', index=4, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CONNECTION_ERROR_ENCRYPTION_ERROR', index=5, number=5,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CONNECTION_ERROR_NAME_IN_USE', index=6, number=6,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CONNECTION_ERROR_INVALID_SETTINGS', index=7, number=7,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CONNECTION_ERROR_CERT_NOT_PROVIDED', index=8, number=8,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CONNECTION_ERROR_CERT_UNTRUSTED', index=9, number=9,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CONNECTION_ERROR_CERT_EXPIRED', index=10, number=10,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CONNECTION_ERROR_CERT_NOT_ACTIVATED', index=11, number=11,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CONNECTION_ERROR_CERT_HOSTNAME_MISMATCH', index=12, number=12,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CONNECTION_ERROR_CERT_FINGERPRINT_MISMATCH', index=13, number=13,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CONNECTION_ERROR_CERT_SELF_SIGNED', index=14, number=14,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CONNECTION_ERROR_CERT_OTHER_ERROR', index=15, number=15,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CONNECTION_ERROR_OTHER_ERROR', index=16, number=16,
      options=None,
      type=None),
  ],
  options=None,
)


_STATUSTYPE = descriptor.EnumDescriptor(
  name='StatusType',
  full_name='pbnetwork.StatusType',
  filename='StatusType',
  values=[
    descriptor.EnumValueDescriptor(
      name='STATUS_ONLINE', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='STATUS_AWAY', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='STATUS_FFC', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='STATUS_XA', index=3, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='STATUS_DND', index=4, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='STATUS_NONE', index=5, number=5,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='STATUS_INVISIBLE', index=6, number=6,
      options=None,
      type=None),
  ],
  options=None,
)


CONNECTION_ERROR_NETWORK_ERROR = 0
CONNECTION_ERROR_INVALID_USERNAME = 1
CONNECTION_ERROR_AUTHENTICATION_FAILED = 2
CONNECTION_ERROR_AUTHENTICATION_IMPOSSIBLE = 3
CONNECTION_ERROR_NO_SSL_SUPPORT = 4
CONNECTION_ERROR_ENCRYPTION_ERROR = 5
CONNECTION_ERROR_NAME_IN_USE = 6
CONNECTION_ERROR_INVALID_SETTINGS = 7
CONNECTION_ERROR_CERT_NOT_PROVIDED = 8
CONNECTION_ERROR_CERT_UNTRUSTED = 9
CONNECTION_ERROR_CERT_EXPIRED = 10
CONNECTION_ERROR_CERT_NOT_ACTIVATED = 11
CONNECTION_ERROR_CERT_HOSTNAME_MISMATCH = 12
CONNECTION_ERROR_CERT_FINGERPRINT_MISMATCH = 13
CONNECTION_ERROR_CERT_SELF_SIGNED = 14
CONNECTION_ERROR_CERT_OTHER_ERROR = 15
CONNECTION_ERROR_OTHER_ERROR = 16
STATUS_ONLINE = 0
STATUS_AWAY = 1
STATUS_FFC = 2
STATUS_XA = 3
STATUS_DND = 4
STATUS_NONE = 5
STATUS_INVISIBLE = 6


_WRAPPERMESSAGE_TYPE = descriptor.EnumDescriptor(
  name='Type',
  full_name='pbnetwork.WrapperMessage.Type',
  filename='Type',
  values=[
    descriptor.EnumValueDescriptor(
      name='TYPE_CONNECTED', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='TYPE_DISCONNECTED', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='TYPE_LOGIN', index=2, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='TYPE_LOGOUT', index=3, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='TYPE_BUDDY_CHANGED', index=4, number=6,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='TYPE_BUDDY_REMOVED', index=5, number=7,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='TYPE_CONV_MESSAGE', index=6, number=8,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='TYPE_PING', index=7, number=9,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='TYPE_PONG', index=8, number=10,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='TYPE_JOIN_ROOM', index=9, number=11,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='TYPE_LEAVE_ROOM', index=10, number=12,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='TYPE_PARTICIPANT_CHANGED', index=11, number=13,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='TYPE_ROOM_NICKNAME_CHANGED', index=12, number=14,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='TYPE_ROOM_SUBJECT_CHANGED', index=13, number=15,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='TYPE_VCARD', index=14, number=16,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='TYPE_STATUS_CHANGED', index=15, number=17,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='TYPE_BUDDY_TYPING', index=16, number=18,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='TYPE_BUDDY_STOPPED_TYPING', index=17, number=19,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='TYPE_BUDDY_TYPED', index=18, number=20,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='TYPE_AUTH_REQUEST', index=19, number=21,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='TYPE_ATTENTION', index=20, number=22,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='TYPE_STATS', index=21, number=23,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='TYPE_FT_START', index=22, number=24,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='TYPE_FT_FINISH', index=23, number=25,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='TYPE_FT_DATA', index=24, number=26,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='TYPE_FT_PAUSE', index=25, number=27,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='TYPE_FT_CONTINUE', index=26, number=28,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='TYPE_EXIT', index=27, number=29,
      options=None,
      type=None),
  ],
  options=None,
)


_CONNECTED = descriptor.Descriptor(
  name='Connected',
  full_name='pbnetwork.Connected',
  filename='protocol.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='user', full_name='pbnetwork.Connected.user', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_DISCONNECTED = descriptor.Descriptor(
  name='Disconnected',
  full_name='pbnetwork.Disconnected',
  filename='protocol.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='user', full_name='pbnetwork.Disconnected.user', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='error', full_name='pbnetwork.Disconnected.error', index=1,
      number=2, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='message', full_name='pbnetwork.Disconnected.message', index=2,
      number=3, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_LOGIN = descriptor.Descriptor(
  name='Login',
  full_name='pbnetwork.Login',
  filename='protocol.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='user', full_name='pbnetwork.Login.user', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='legacyName', full_name='pbnetwork.Login.legacyName', index=1,
      number=2, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='password', full_name='pbnetwork.Login.password', index=2,
      number=3, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_LOGOUT = descriptor.Descriptor(
  name='Logout',
  full_name='pbnetwork.Logout',
  filename='protocol.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='user', full_name='pbnetwork.Logout.user', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='legacyName', full_name='pbnetwork.Logout.legacyName', index=1,
      number=2, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_BUDDY = descriptor.Descriptor(
  name='Buddy',
  full_name='pbnetwork.Buddy',
  filename='protocol.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='userName', full_name='pbnetwork.Buddy.userName', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='buddyName', full_name='pbnetwork.Buddy.buddyName', index=1,
      number=2, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='alias', full_name='pbnetwork.Buddy.alias', index=2,
      number=3, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='group', full_name='pbnetwork.Buddy.group', index=3,
      number=4, type=9, cpp_type=9, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='status', full_name='pbnetwork.Buddy.status', index=4,
      number=5, type=14, cpp_type=8, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='statusMessage', full_name='pbnetwork.Buddy.statusMessage', index=5,
      number=6, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='iconHash', full_name='pbnetwork.Buddy.iconHash', index=6,
      number=7, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='blocked', full_name='pbnetwork.Buddy.blocked', index=7,
      number=8, type=8, cpp_type=7, label=1,
      default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_CONVERSATIONMESSAGE = descriptor.Descriptor(
  name='ConversationMessage',
  full_name='pbnetwork.ConversationMessage',
  filename='protocol.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='userName', full_name='pbnetwork.ConversationMessage.userName', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='buddyName', full_name='pbnetwork.ConversationMessage.buddyName', index=1,
      number=2, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='message', full_name='pbnetwork.ConversationMessage.message', index=2,
      number=3, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='nickname', full_name='pbnetwork.ConversationMessage.nickname', index=3,
      number=4, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='xhtml', full_name='pbnetwork.ConversationMessage.xhtml', index=4,
      number=5, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_ROOM = descriptor.Descriptor(
  name='Room',
  full_name='pbnetwork.Room',
  filename='protocol.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='userName', full_name='pbnetwork.Room.userName', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='nickname', full_name='pbnetwork.Room.nickname', index=1,
      number=2, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='room', full_name='pbnetwork.Room.room', index=2,
      number=3, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='password', full_name='pbnetwork.Room.password', index=3,
      number=4, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_PARTICIPANT = descriptor.Descriptor(
  name='Participant',
  full_name='pbnetwork.Participant',
  filename='protocol.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='userName', full_name='pbnetwork.Participant.userName', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='room', full_name='pbnetwork.Participant.room', index=1,
      number=2, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='nickname', full_name='pbnetwork.Participant.nickname', index=2,
      number=3, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='flag', full_name='pbnetwork.Participant.flag', index=3,
      number=4, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='status', full_name='pbnetwork.Participant.status', index=4,
      number=5, type=14, cpp_type=8, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='statusMessage', full_name='pbnetwork.Participant.statusMessage', index=5,
      number=6, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='newname', full_name='pbnetwork.Participant.newname', index=6,
      number=7, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_VCARD = descriptor.Descriptor(
  name='VCard',
  full_name='pbnetwork.VCard',
  filename='protocol.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='userName', full_name='pbnetwork.VCard.userName', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='buddyName', full_name='pbnetwork.VCard.buddyName', index=1,
      number=2, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='id', full_name='pbnetwork.VCard.id', index=2,
      number=3, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='fullname', full_name='pbnetwork.VCard.fullname', index=3,
      number=4, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='nickname', full_name='pbnetwork.VCard.nickname', index=4,
      number=5, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='photo', full_name='pbnetwork.VCard.photo', index=5,
      number=6, type=12, cpp_type=9, label=1,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_STATUS = descriptor.Descriptor(
  name='Status',
  full_name='pbnetwork.Status',
  filename='protocol.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='userName', full_name='pbnetwork.Status.userName', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='status', full_name='pbnetwork.Status.status', index=1,
      number=3, type=14, cpp_type=8, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='statusMessage', full_name='pbnetwork.Status.statusMessage', index=2,
      number=4, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_STATS = descriptor.Descriptor(
  name='Stats',
  full_name='pbnetwork.Stats',
  filename='protocol.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='res', full_name='pbnetwork.Stats.res', index=0,
      number=1, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='init_res', full_name='pbnetwork.Stats.init_res', index=1,
      number=2, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='shared', full_name='pbnetwork.Stats.shared', index=2,
      number=3, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='id', full_name='pbnetwork.Stats.id', index=3,
      number=4, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_FILE = descriptor.Descriptor(
  name='File',
  full_name='pbnetwork.File',
  filename='protocol.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='userName', full_name='pbnetwork.File.userName', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='buddyName', full_name='pbnetwork.File.buddyName', index=1,
      number=2, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='fileName', full_name='pbnetwork.File.fileName', index=2,
      number=3, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='size', full_name='pbnetwork.File.size', index=3,
      number=4, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ftID', full_name='pbnetwork.File.ftID', index=4,
      number=5, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_FILETRANSFERDATA = descriptor.Descriptor(
  name='FileTransferData',
  full_name='pbnetwork.FileTransferData',
  filename='protocol.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='ftID', full_name='pbnetwork.FileTransferData.ftID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='data', full_name='pbnetwork.FileTransferData.data', index=1,
      number=2, type=12, cpp_type=9, label=2,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_WRAPPERMESSAGE = descriptor.Descriptor(
  name='WrapperMessage',
  full_name='pbnetwork.WrapperMessage',
  filename='protocol.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='pbnetwork.WrapperMessage.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='payload', full_name='pbnetwork.WrapperMessage.payload', index=1,
      number=2, type=12, cpp_type=9, label=1,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
    _WRAPPERMESSAGE_TYPE,
  ],
  options=None)


_BUDDY.fields_by_name['status'].enum_type = _STATUSTYPE
_PARTICIPANT.fields_by_name['status'].enum_type = _STATUSTYPE
_STATUS.fields_by_name['status'].enum_type = _STATUSTYPE
_WRAPPERMESSAGE.fields_by_name['type'].enum_type = _WRAPPERMESSAGE_TYPE

class Connected(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CONNECTED

class Disconnected(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DISCONNECTED

class Login(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LOGIN

class Logout(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LOGOUT

class Buddy(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BUDDY

class ConversationMessage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CONVERSATIONMESSAGE

class Room(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ROOM

class Participant(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PARTICIPANT

class VCard(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _VCARD

class Status(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _STATUS

class Stats(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _STATS

class File(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FILE

class FileTransferData(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FILETRANSFERDATA

class WrapperMessage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _WRAPPERMESSAGE

